version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: Mariadb:10.8.3

    environment:
        MYSQL_ROOT_PASSWORD: root

    ports:
      - '3306'


      # You should definitely change the password in production
      
    volumes:
      - mysql:/var/lib/mysql

      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes: 
###> doctrine/doctrine-bundle ###
   mysql:
###< doctrine/doctrine-bundle ###
